extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "../build/local_value_numbering",
    "brili -p {args}",
]

[runs.lvn_commutative]
pipeline = [
    "bril2json",
    "../build/local_value_numbering -c",
    "brili -p {args}",
]

[runs.lvn_constant_folding]
pipeline = [
    "bril2json",
    "../build/local_value_numbering -f",
    "brili -p {args}",
]

[runs.lvn_algebraic_identity]
pipeline = [
    "bril2json",
    "../build/local_value_numbering -a",
    "brili -p {args}",
]

[runs.lvn_all]
pipeline = [
    "bril2json",
    "../build/local_value_numbering -c -f -a",
    "brili -p {args}",
]